import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import Navbar from '../components/Navbar'

export default function You() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Avatar />
      <h1>You &lt;3</h1>
    </>
  )
}
